import React, { useState, useEffect } from 'react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer } from 'recharts';
import { useLocation, useNavigate } from 'react-router-dom';
import pptxgen from 'pptxgenjs';
import { Download, Loader2 } from 'lucide-react';
import ChatWidget from '../components/ChatWidget';

const fallbackPerformanceData = [
  { name: 'Jan', revenue: 4000, target: 2400 },
  { name: 'Feb', revenue: 3000, target: 1398 },
  { name: 'Mar', revenue: 2000, target: 9800 }
];
const fallbackMetricData = [
  { name: 'Q1', growth: 85, attrition: 15 },
  { name: 'Q2', growth: 72, attrition: 18 }
];

const GeneralReportView = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [isExporting, setIsExporting] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [dynamicData, setDynamicData] = useState<any>(null);

  const sources: string[] = location.state?.sources || ['uploaded_file.csv'];
  const dynamicTitle = location.state?.reportTitle || "General Performance Report";
  const fileData = location.state?.fileData || "";

  useEffect(() => {
    if (!fileData) {
      setIsLoading(false);
      return;
    }

    const generateDynamicLayout = async () => {
      try {
        const prompt = `You are a dashboard generator. Based on this CSV data snippet:\n\n${fileData}\n\nGenerate a JSON object strictly matching this schema. DO NOT wrap it in markdown block quotes. ONLY return raw JSON:
{
  "kpis": [
    { "label": "String (e.g. Total Customers)", "value": "String (e.g. 1,450)", "subtext": "String (e.g. +5% vs prev)" } // Exactly 3 KPIs
  ],
  "chart1": {
    "title": "String",
    "data": [ { "name": "Category", "val1": 10 } ], // 3-7 items
    "lineKey": "val1"
  },
  "chart2": {
    "title": "String",
    "data": [ { "name": "Category", "val1": 20, "val2": 15 } ], // 3-7 items
    "barKey1": "val1",
    "barKey2": "val2"
  }
}`;
        const res = await fetch('http://localhost:3001/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ message: prompt })
        });
        const data = await res.json();
        const jsonStr = data.reply.replace(/```json/g, '').replace(/```/g, '').trim();
        const parsed = JSON.parse(jsonStr);
        setDynamicData(parsed);
      } catch (err) {
        console.error("Failed to parse dynamic JSON", err);
      } finally {
        setIsLoading(false);
      }
    };
    generateDynamicLayout();
  }, [fileData]);

  const exportToPPT = () => {
    setIsExporting(true);
    let pres = new pptxgen();
    
    // Slide 1: Title
    let slide1 = pres.addSlide();
    slide1.background = { color: 'F8FAFC' };
    slide1.addText(dynamicTitle, {
      x: 1, y: 1.5, w: '80%', h: 1,
      fontSize: 32, bold: true, color: '1E293B', align: 'center'
    });
    slide1.addText("Generated by AI Presentation System", {
      x: 1, y: 2.5, w: '80%', h: 0.5,
      fontSize: 16, color: '64748B', align: 'center'
    });
    
    // Slide 2: Executive Summary
    let slide2 = pres.addSlide();
    slide2.addText("Executive Summary", { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '1E293B' });
    slide2.addText([
      { text: `Metrics for ${dynamicTitle} show solid performance.`, options: { bullet: true } },
      { text: "Detailed breakdowns align with expected variations.", options: { bullet: true } }
    ], { x: 0.5, y: 1.2, w: '80%', h: 3, fontSize: 18, color: '334155' });
    
    pres.writeFile({ fileName: `${dynamicTitle.replace(/\s+/g, '_')}.pptx` })
      .then(() => setIsExporting(false))
      .catch((e) => {
        console.error(e);
        setIsExporting(false);
      });
  };

  const reportContext = JSON.stringify({
    reportType: dynamicTitle,
    dataPreview: dynamicData || "No parsed data available"
  });

  if (isLoading) {
    return (
      <div className="max-w-6xl mx-auto p-8 flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <Loader2 className="w-10 h-10 text-indigo-600 animate-spin" />
        <h2 className="text-xl font-bold text-gray-800 animate-pulse">Analyzing file structure & generating dynamic dashboard...</h2>
      </div>
    );
  }

  // Use dynamic data or fallback to a basic placeholder if LLM failed
  const kpis = dynamicData?.kpis || [
    { label: "Data Rows", value: "Loaded", subtext: "Processed properly" },
    { label: "Format", value: "CSV", subtext: "Standard tabular" },
    { label: "Status", value: "Active", subtext: "Live session" }
  ];
  
  const chart1 = dynamicData?.chart1 || {
    title: "Primary Trend",
    data: fallbackPerformanceData,
    lineKey: "revenue"
  };

  const chart2 = dynamicData?.chart2 || {
    title: "Category Distribution",
    data: fallbackMetricData,
    barKey1: "growth",
    barKey2: "attrition"
  };

  return (
    <div className="max-w-6xl mx-auto p-8 pb-20">
      {/* Header */}
      <div className="bg-indigo-900 text-white rounded-xl p-6 mb-8 shadow-sm">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold mb-1">{dynamicTitle}</h1>
            <p className="text-sm text-indigo-200 mb-4">Based on data from: {sources.join(', ')}</p>
          </div>
          <div className="flex gap-3">
            <button 
              onClick={() => navigate('/')}
              className="flex items-center gap-2 bg-indigo-800 hover:bg-indigo-700 border border-indigo-600 px-4 py-2 rounded transition text-sm font-medium"
            >
              Back to Home
            </button>
            <button 
              onClick={exportToPPT}
              disabled={isExporting}
              className="flex items-center gap-2 bg-white text-indigo-900 hover:bg-indigo-50 px-4 py-2 rounded font-semibold transition"
            >
              {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download size={18} />}
              Export to PPT
            </button>
          </div>
        </div>
      </div>

      {/* Dynamic KPIs */}
      <div className="grid grid-cols-3 gap-6 mb-8">
        {kpis.map((kpi: any, idx: number) => (
          <div key={idx} className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm flex flex-col justify-center">
            <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">{kpi.label}</p>
            <h3 className="text-3xl font-black text-gray-800 mb-1">{kpi.value}</h3>
            <p className="text-sm font-medium text-green-600">{kpi.subtext}</p>
          </div>
        ))}
      </div>

      {/* Dynamic Charts Grid */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        
        {/* Dynamic Line Chart */}
        <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-semibold text-gray-700 mb-6">{chart1.title}</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={chart1.data}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                <RechartsTooltip contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'}} />
                <Legend iconType="circle" wrapperStyle={{paddingTop: '20px'}} />
                <Line type="monotone" dataKey={chart1.lineKey} stroke="#4F46E5" strokeWidth={3} dot={{r: 4, strokeWidth: 2}} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Dynamic Bar Chart */}
        <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-semibold text-gray-700 mb-6">{chart2.title}</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chart2.data} barSize={40}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                <RechartsTooltip cursor={{fill: '#F3F4F6'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'}} />
                <Legend iconType="circle" wrapperStyle={{paddingTop: '10px'}} />
                <Bar name={chart2.barKey1} dataKey={chart2.barKey1} fill="#10B981" radius={[4, 4, 0, 0]} />
                {chart2.barKey2 && <Bar name={chart2.barKey2} dataKey={chart2.barKey2} fill="#F43F5E" radius={[4, 4, 0, 0]} />}
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <ChatWidget context={reportContext} title={`${dynamicTitle} Assistant`} />
    </div>
  );
};

export default GeneralReportView;
